### ISSUE TITLE
Store reports - Action failed with "not found deploy key or tokens"

### ISSUE THREAD

**Issue by bremnes** [staticwebdev/nextjs-starter#35]
Following the tutorial at https://docs.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs causes the github action/build `Playwright tests` to fail on the steps "store reports" and "notify dashboard". I'm not familiar with these actions, but it looks like there is some publishing going on to `mspnp/intern-js-pipeline` which I'm assuming all users don't have access to.

```yaml
...
    - name: Publish to external repo
      if: always()
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        external_repository: mspnp/intern-js-pipeline
        publish_branch: gh-pages
        personal_token: ${{ secrets.PAT_TOKEN }}
        publish_dir: ${{steps.download.outputs.download-path}}
        destination_dir: test-reports/${{ github.repository }}
        keep_files: true
        user_name: "github-actions[bot]"
        user_email: "github-actions[bot]@users.noreply.github.com"
...
```

![image](https://user-images.githubusercontent.com/3669798/184676280-014bc6ac-0646-4d35-9394-9964c34c16c3.png)

Related PR: https://github.com/staticwebdev/nextjs-starter/pull/34

Misc.:
- The forked repository is a private repository
- Setup between github and Azure Static Web App works fine, and the workflow in `.github\workflow\azure-static-web-apps-<random>.yml` deploys the static code to both production and preview deployments fine.

Let me know if you need any more input.
